- id: nfs-service_vip
  type: group
  role: [nfs-service]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
      hosts, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts, cluster,
      virtual_ips]
  parameters:
    strategy:
      type: one_by_one

- id: deploy-nfs-service
  type: puppet
  role: [nfs-service]
  requires: [globals]
  required_for: [cluster]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
      hosts, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts, cluster,
      virtual_ips]
  parameters:
    puppet_manifest: deploy-nfs-service-override.pp
    puppet_modules: /etc/puppet/modules
    timeout: 600

- id: deploy-nfs-client
  type: puppet
  role: [controller]
  requires: [globals]
  required_for: [cluster]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
      hosts, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts, cluster,
      virtual_ips]
  parameters:
    puppet_manifest: deploy-nfs-client-override.pp
    puppet_modules: /etc/puppet/modules
    timeout: 600

