#version 2.0.0 -flag for TBD, if anyone task dont have this
#flag, nailgun start Granular deploy
- id: nfs-service
  type: group
  version: 2.0.0
  role: [nfs-service]
  requires: [deploy_start]
  required_for:
    - deploy_end
    - controller
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
          hosts, firewall]
  parameters:
    strategy:
     type: parallel

- id: deploy-nfs-service
  type: puppet
  version: 2.0.0
  groups: [nfs-service_vip, nfs-service]
  role: [nfs-service]
  requires: [deploy_start, netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/deploy-nfs-service-override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 600

- id: deploy-clients-nfs
  type: puppet
  version: 2.0.0
  cross-depended-by:
    - name: /deploy-nfs-service/
  role: [primary-controller, controller, cinder]
  requires: [deploy_start, netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/deploy-nfs-client-override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 600
