- id: nfs-service_vip
  type: group
  role: [nfs-service]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
      hosts, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts, cluster,
      virtual_ips]
  parameters:
    strategy:
      type: one_by_one

- id: nfs-service
  type: group
  role: [nfs-service]
  requires: [deploy_start]
  required_for:
    - deploy_end
    - controller
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
          hosts, firewall]
  parameters:
    strategy:
     type: parallel

- id: deploy-nfs-service
  type: puppet
  groups: [nfs-service_vip, nfs-service]
  role: [nfs-service]
<<<<<<< HEAD
  requires: [deploy_start]
=======
  requires: [netconfig]
>>>>>>> 6fece3572db67d4fe920862b195c99d17c651b14
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/deploy-nfs-service-override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: deploy-cinder-nfs
  type: puppet
<<<<<<< HEAD
  role: [cinder]
  requires: [deploy_start]
=======
  role: [controller]
  requires: [netconfig]
>>>>>>> 6fece3572db67d4fe920862b195c99d17c651b14
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/deploy-nfs-client-override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules/"
    timeout: 3600

- id: deploy-controller-nfs
  type: puppet
  role: [primary-controller, controller]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/deploy-nfs-client-override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules/"
    timeout: 3600
