- id: nfs-service
  type: group
  role: [nfs-service]
  requires: [deploy_start]
  required_for:
    - deploy_end
    - controller
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
          hosts, firewall]
  parameters:
    strategy:
     type: one_by_one

- id: deploy-nfs-service
  type: puppet
  groups: [nfs-service_vip, nfs-service]
  role: [nfs-service]
  requires: [deploy_start]
  requires: [netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/deploy-nfs-service-override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 600

- id: deploy-clients-nfs
  type: puppet
  role: [primary-controller, controller, cinder]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/deploy-nfs-client-override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 600
